### ISSUE TITLE
figcaption as part of name and description calcualtion?

### ISSUE THREAD

**Issue by mbgower** [w3c/accname#181]
Just wondering if there's been any consideration of using the value of figcaption in the computation for either name or description.

The simplistic example on MDN's [figcaption topic](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption#:~:text=The%20HTML%20element%20represents,its%20parent%20element.) illustrates the current situation. Despite the fact the information is already supplied using figcaption, the author has been forced to use a specific alt of virtually the same value. Seems pretty redundant.
> <figure>
    <img src="/media/cc0-images/elephant-660-480.jpg"
         alt="Elephant at sunset">
    <figcaption>An elephant at sunset</figcaption>
</figure>

Yes, there may be cases where the caption is not sufficient as an alt, but to me it would be _highly_ unusual that the figcaption does not in some way describe the image. Therefore I'd suggest that if it was at the bottom of the computation, where all other ALT methods don't work, it could be considered (much like title), and where there is another alt, it could be considered a description.

**Comment by scottaohara** [comment]
@mbgower you've opened this issue before in 2021 and it was transferred to HTML AAM, which is where this topic belongs since it's about the naming of a specific HTML feature - https://github.com/w3c/html-aam/issues/325

the MDN example should change, because it's a poor use of figcaption.  it shouldn't be the name of an image, but rather additional details about the image.

Unfortunately, the PR for the resolved change to the previous issue stalled out due to getting the proper UIA mappings in place. 

I'm closing this issue since it's duplicate to the previous one.  discussion can continue in there if necessary.
