### ISSUE TITLE
Clarify last sentence and vs. or?

### ISSUE THREAD

**Issue by kengdoj** [w3c/accname#81]
Hello,

This last sentence is causing some confusion:

> After all steps are completed, the total accumulated text is used as the accessible name or accessible description of the element that initiated the computation.

However, the computation instructions end with:

> Append the result of each step above, with a space, to the total accumulated text.

Wouldn't this mean that the total accumulated text is the computed accessible name _and_ computed accessible description, not _or_?

Can you please clarify: is the text alternative (which is the total accumulated text) the accessible name _and_ the accessible description?

Thank you!

**Comment by JAWS-test** [comment]
Before going through the steps, it must be decided whether a name or a description should be determined ([4.1](https://w3c.github.io/accname/#mapping_additional_nd_name) or [4.2](https://w3c.github.io/accname/#mapping_additional_nd_description)). For some steps it makes a difference whether a name or description is determined (e.g. 2B "if computing a name, ... or, if computing a description", ). Therefore "or" is correct at the end. Only name or description is determined, never both.

**Comment by carmacleod** [comment]
@kengdoj 
> Does text alternative = accessible name and accessible description?

- When calculating an accessible name, text alternative = accessible name.
- When calculating an accessible description, text alternative = accessible description.

Hope this helps!

(Also, there is work ongoing in https://github.com/w3c/accname/pull/69 to clarify some of the wording here, so hopefully in the near future this will be easier to read).

**Comment by kengdoj** [comment]
Thanks, @carmacleod. It helps for sure to clarify the steps of the computation. After computations, there would be 2 text alternatives found for a given element.  

Is it accurate then to say that both the accessible name and the accessible description make up the text alternative for a given element? 

(Sorry to dig for this detail, but this is where the confusion is for our team.)

**Comment by JAWS-test** [comment]
For each element the process can be run through twice: once for name and once for description. In the end, two text alternatives are determined (which can also be empty). Note: In my opinion, the term text alternative is used in the WCAG only for the name and not for the description. If an element has no name and only a description, this is a violation of the WCAG (SC 1.1.1, 4.1.2 etc.)

**Comment by carmacleod** [comment]
@kengdoj 

Does @JAWS-test's comment https://github.com/w3c/accname/issues/81#issuecomment-622243508 clarify this point for your team? If so, maybe we can close this issue?

**Comment by kengdoj** [comment]
Yes, thanks @JAWS-test  and @carmacleod, this does answer my initial question. 

But the other point that was brought up by @JAWS-test was also a question my team had: is text alternative _only_ accessible name in WCAG? If this is not the appropriate place to get an answer for this question, would you please suggest where it should be asked? 

Thank you again!

**Comment by carmacleod** [comment]
I see where the confusion is. [WCAG's definition of text alternative](https://w3c.github.io/wcag21/guidelines/#dfn-text-alternative) and the [understanding paragraph for text alternative](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance#uc-text-alternatives-head) don't explicitly say "accessible name" or "accessible description".

Looking at the [Techniques for SC 1.1.1](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=111#non-text-content), I see that many of them say either "short text alternative", "label", "purpose", "accepted name", descriptive name", "brief description", "descriptive label" or "short description" when they mean _**"accessible name"**_.

They say "long text alternative", "long description", "longer description" or "longer text description" when they mean _**"accessible description"**_.

WCAG is hard to read. 😄 They're working on that with [WCAG Silver](https://www.w3.org/WAI/GL/task-forces/silver/wiki/Welcome_to_Silver#Usability).
ACCNAME (this spec) is hard to read, too. We're working on that. :)

**In general,**
- name is required on many (but not all) elements (and there are many different techniques to add a name)
- description is typically optional, although if an element _has_ a description (visible or otherwise), you will want to make sure its description can be programmatically determined (there are several different techniques to do that as well)

Your team may find section [5. Providing Accessible Names and Descriptions](https://w3c.github.io/aria-practices/#names_and_descriptions) of the APG helpful. It says:
> Both the WAI-ARIA specification and WCAG require all focusable, interactive elements to have an accessible name. In addition dialogs and some structural containers, such as tables and regions, are required to have a name.

For guidance about which specific roles need a name, refer to the table in [Accessible Name Guidance by Role](https://w3c.github.io/aria-practices/#naming_role_guidance). Please don't be confused by the fact that it is listed by ARIA role, and not by HTML element tag. If needed, here's the [mapping from each HTML element to its default ARIA role](https://w3c.github.io/html-aam/#html-element-role-mappings).

In addition, I highly recommend @smhigley's article [What's in a name?](https://sarahmhigley.com/writing/whats-in-a-name/) for a much friendlier and less "spec-oriented" look at naming your elements. :)

**Comment by JAWS-test** [comment]
> They say "long text alternative", "long description", "longer description" or "longer text description" when they mean "accessible description".

Sometimes that's true, but not always. For example, the alternative text of graphics should not be longer than 80 characters. If the graphic is complex, a distinction is made between a short alternative text in the alt attribute (e.g. "chart: Sales in the years 2010 to 2020") and a long text alternative, which is linked, for example, and which transmits the chart data in tabular form. The table is then not a description in the sense of ACC NAME, but a separate text alternative (see https://www.w3.org/WAI/WCAG21/Techniques/general/G73, https://www.w3.org/WAI/tutorials/images/complex/).

**Comment by carmacleod** [comment]
> Sometimes that's true, but not always.

Ok, I've updated my response and added "seem to" for the list of phrases that WCAG seems to be using for name and description in SC 1.1.1 (which is just one example). The point is that the WCAG phrasing is varied, and the specific phrase "text alternative" is only roughly related to ACCNAME's "text alternative".

@kengdoj Hopefully we have been helpful, and this issue can be closed.

**Comment by kengdoj** [comment]
Thank you @carmacleod and @JAWS-test. Your replies have been very helpful and I appreciate your time and expertise!

I will close the issue. My team is testing for conformance, and it would be tremendously helpful to find something normative that states accessible name is required. We don't want to fail anything unless it's clearly stated as a requirement.

**Comment by JAWS-test** [comment]
> it would be tremendously helpful to find something normative that states accessible name is required

You can find it in SC 4.1.2: https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html
And SC 2.5.3 refers to "Accessible Name" and links to ACC NAME (https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html)

**Comment by bruce-usab** [comment]
I am so glad to see detail under active discussion.

@carmacleod  noted where the confusion is:
> WCAG's definition of text alternative and the understanding paragraph for text alternative don't explicitly say "accessible name" or "accessible description".

SC 1.1.1 is very permissive.  Technically, it does not even fail _missing_ ALT attributes if the textual equivalent is in body prose.  Also keep in mind that WCAG 2.0 (2008) significantly predates WAI-ARIA 1.0 (2014).

I like @JAWS-test idea about failing missing accessible name against 4.1.2 instead.
